#include <stdio.h>
#include <stdlib.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main()
{
    int num=1,num1=2,soma_P=0,soma=0,num2=2;
    for(int i=0;i<4000000;i++){
        if(num1>=4000000){
            i=4000001;
            break;
        }else{
        num2=num+num1;
        num=num1;
        num1=num2;
        if(num2%2==0){
            soma_P=soma_P+num2;
        }
        }
    printf("%d\n",soma_P+2);
    }
    return 0;
}
